package ext.datasource.inf;

import ext.datasource.entity.BusnessItem;
import ext.datasource.entity.BusnessItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusnessItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    long countByExample(BusnessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int deleteByExample(BusnessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int insert(BusnessItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int insertSelective(BusnessItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    List<BusnessItem> selectByExample(BusnessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    BusnessItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") BusnessItem record, @Param("example") BusnessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByExample(@Param("record") BusnessItem record, @Param("example") BusnessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(BusnessItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ITEM
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByPrimaryKey(BusnessItem record);
}