package ext.datasource.inf;

import ext.datasource.entity.BusnessOrder;
import ext.datasource.entity.BusnessOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusnessOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    long countByExample(BusnessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int deleteByExample(BusnessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int insert(BusnessOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int insertSelective(BusnessOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    List<BusnessOrder> selectByExample(BusnessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    BusnessOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") BusnessOrder record, @Param("example") BusnessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByExample(@Param("record") BusnessOrder record, @Param("example") BusnessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(BusnessOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSNESS_ORDER
     *
     * @mbg.generated Thu Jun 01 01:40:55 GMT+08:00 2017
     */
    int updateByPrimaryKey(BusnessOrder record);
}