package ext.datasource.inf;

import ext.datasource.entity.RequestInfo;
import ext.datasource.entity.RequestInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	long countByExample(RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int deleteByExample(RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int insert(RequestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int insertSelective(RequestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	List<RequestInfo> selectByExample(RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	RequestInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") RequestInfo record, @Param("example") RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") RequestInfo record, @Param("example") RequestInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(RequestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUEST_INFO
	 * @mbg.generated  Thu Jun 29 16:38:26 GMT+08:00 2017
	 */
	int updateByPrimaryKey(RequestInfo record);
}