package ext.datasource.inf;

import ext.datasource.entity.SModule;
import ext.datasource.entity.SModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_MODULE
     *
     * @mbg.generated Tue Jun 13 03:21:14 GMT+08:00 2017
     */
    long countByExample(SModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_MODULE
     *
     * @mbg.generated Tue Jun 13 03:21:14 GMT+08:00 2017
     */
    int deleteByExample(SModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_MODULE
     *
     * @mbg.generated Tue Jun 13 03:21:14 GMT+08:00 2017
     */
    int insert(SModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_MODULE
     *
     * @mbg.generated Tue Jun 13 03:21:14 GMT+08:00 2017
     */
    int insertSelective(SModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_MODULE
     *
     * @mbg.generated Tue Jun 13 03:21:14 GMT+08:00 2017
     */
    List<SModule> selectByExample(SModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_MODULE
     *
     * @mbg.generated Tue Jun 13 03:21:14 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") SModule record, @Param("example") SModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_MODULE
     *
     * @mbg.generated Tue Jun 13 03:21:14 GMT+08:00 2017
     */
    int updateByExample(@Param("record") SModule record, @Param("example") SModuleExample example);
}