package ext.datasource.inf;

import ext.datasource.entity.SRequest;
import ext.datasource.entity.SRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    long countByExample(SRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int deleteByExample(SRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int insert(SRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int insertSelective(SRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    List<SRequest> selectByExample(SRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    SRequest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") SRequest record, @Param("example") SRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int updateByExample(@Param("record") SRequest record, @Param("example") SRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(SRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_REQUEST
     *
     * @mbg.generated Thu Jun 29 13:43:32 GMT+08:00 2017
     */
    int updateByPrimaryKey(SRequest record);
}