package ext.datasource.inf;

import ext.datasource.entity.SRole;
import ext.datasource.entity.SRoleExample;
import ext.datasource.entity.SRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	long countByExample(SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int deleteByExample(SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(SRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int insert(SRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int insertSelective(SRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	List<SRole> selectByExample(SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	SRole selectByPrimaryKey(SRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") SRole record, @Param("example") SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") SRole record, @Param("example") SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(SRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByPrimaryKey(SRole record);
}