package ext.datasource.inf;

import ext.datasource.entity.SUser;
import ext.datasource.entity.SUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SUserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	long countByExample(SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int deleteByExample(SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int insert(SUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int insertSelective(SUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	List<SUser> selectByExample(SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	SUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") SUser record, @Param("example") SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") SUser record, @Param("example") SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(SUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_USER
	 * @mbg.generated  Tue Jun 13 03:21:14 GMT+08:00 2017
	 */
	int updateByPrimaryKey(SUser record);

	/**
     * get the user through username and pwd
     */
     SUser getUser(String userName ,String pwd)	  	;
}