package ext.datasource.inf;

import ext.datasource.entity.TrxClass;
import ext.datasource.entity.TrxClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrxClassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	long countByExample(TrxClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int deleteByExample(TrxClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int insert(TrxClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int insertSelective(TrxClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	List<TrxClass> selectByExample(TrxClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	TrxClass selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") TrxClass record, @Param("example") TrxClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") TrxClass record, @Param("example") TrxClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(TrxClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_CLASS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	int updateByPrimaryKey(TrxClass record);
}