package ext.datasource.inf;

import ext.datasource.entity.TrxDuty;
import ext.datasource.entity.TrxDutyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrxDutyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	long countByExample(TrxDutyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int deleteByExample(TrxDutyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int insert(TrxDuty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int insertSelective(TrxDuty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	List<TrxDuty> selectByExample(TrxDutyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	TrxDuty selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") TrxDuty record, @Param("example") TrxDutyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") TrxDuty record, @Param("example") TrxDutyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(TrxDuty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TRX_DUTY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	int updateByPrimaryKey(TrxDuty record);
}