package ext.datasource.entity;

import java.util.Date;

public class ClassRel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.CUSTOMER_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.CLASS_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Integer classId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Integer createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Integer updateOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS_REL.CONTRACT_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	private Integer contractId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.ID
	 * @return  the value of TRX_CLASS_REL.ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.ID
	 * @param id  the value for TRX_CLASS_REL.ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.CUSTOMER_ID
	 * @return  the value of TRX_CLASS_REL.CUSTOMER_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.CUSTOMER_ID
	 * @param customerId  the value for TRX_CLASS_REL.CUSTOMER_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.CLASS_ID
	 * @return  the value of TRX_CLASS_REL.CLASS_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Integer getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.CLASS_ID
	 * @param classId  the value for TRX_CLASS_REL.CLASS_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.CREATE_DATE
	 * @return  the value of TRX_CLASS_REL.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.CREATE_DATE
	 * @param createDate  the value for TRX_CLASS_REL.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.CREATE_OPERATOR
	 * @return  the value of TRX_CLASS_REL.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Integer getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.CREATE_OPERATOR
	 * @param createOperator  the value for TRX_CLASS_REL.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setCreateOperator(Integer createOperator) {
		this.createOperator = createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.UPDATE_DATE
	 * @return  the value of TRX_CLASS_REL.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.UPDATE_DATE
	 * @param updateDate  the value for TRX_CLASS_REL.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.UPDATE_OPERATOR
	 * @return  the value of TRX_CLASS_REL.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Integer getUpdateOperator() {
		return updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.UPDATE_OPERATOR
	 * @param updateOperator  the value for TRX_CLASS_REL.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setUpdateOperator(Integer updateOperator) {
		this.updateOperator = updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS_REL.CONTRACT_ID
	 * @return  the value of TRX_CLASS_REL.CONTRACT_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public Integer getContractId() {
		return contractId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS_REL.CONTRACT_ID
	 * @param contractId  the value for TRX_CLASS_REL.CONTRACT_ID
	 * @mbg.generated  Tue Jun 27 20:57:54 GMT+08:00 2017
	 */
	public void setContractId(Integer contractId) {
		this.contractId = contractId;
	}
}