package ext.datasource.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import ext.util.helper.CustomDateSerializer;

public class Contract {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.CUSTOMER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.CUSTOMER_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.EXECUTE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date executeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer updateOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.CONTRACT_AMT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private BigDecimal contractAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.CONTRACT_BALANCE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private BigDecimal contractBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.CONTRACT_STATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer contractState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CONTRACT.NOTE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.ID
	 * @return  the value of TRX_CONTRACT.ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.ID
	 * @param id  the value for TRX_CONTRACT.ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.CUSTOMER_ID
	 * @return  the value of TRX_CONTRACT.CUSTOMER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.CUSTOMER_ID
	 * @param customerId  the value for TRX_CONTRACT.CUSTOMER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.CUSTOMER_NAME
	 * @return  the value of TRX_CONTRACT.CUSTOMER_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.CUSTOMER_NAME
	 * @param customerName  the value for TRX_CONTRACT.CUSTOMER_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.EXECUTE_DATE
	 * @return  the value of TRX_CONTRACT.EXECUTE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getExecuteDate() {
		return executeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.EXECUTE_DATE
	 * @param executeDate  the value for TRX_CONTRACT.EXECUTE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setExecuteDate(Date executeDate) {
		this.executeDate = executeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.CREATE_DATE
	 * @return  the value of TRX_CONTRACT.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.CREATE_DATE
	 * @param createDate  the value for TRX_CONTRACT.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.CREATE_OPERATOR
	 * @return  the value of TRX_CONTRACT.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.CREATE_OPERATOR
	 * @param createOperator  the value for TRX_CONTRACT.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCreateOperator(Integer createOperator) {
		this.createOperator = createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.UPDATE_DATE
	 * @return  the value of TRX_CONTRACT.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.UPDATE_DATE
	 * @param updateDate  the value for TRX_CONTRACT.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.UPDATE_OPERATOR
	 * @return  the value of TRX_CONTRACT.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getUpdateOperator() {
		return updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.UPDATE_OPERATOR
	 * @param updateOperator  the value for TRX_CONTRACT.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setUpdateOperator(Integer updateOperator) {
		this.updateOperator = updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.CONTRACT_AMT
	 * @return  the value of TRX_CONTRACT.CONTRACT_AMT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public BigDecimal getContractAmt() {
		return contractAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.CONTRACT_AMT
	 * @param contractAmt  the value for TRX_CONTRACT.CONTRACT_AMT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setContractAmt(BigDecimal contractAmt) {
		this.contractAmt = contractAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.CONTRACT_BALANCE
	 * @return  the value of TRX_CONTRACT.CONTRACT_BALANCE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public BigDecimal getContractBalance() {
		return contractBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.CONTRACT_BALANCE
	 * @param contractBalance  the value for TRX_CONTRACT.CONTRACT_BALANCE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setContractBalance(BigDecimal contractBalance) {
		this.contractBalance = contractBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.CONTRACT_STATE
	 * @return  the value of TRX_CONTRACT.CONTRACT_STATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getContractState() {
		return contractState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.CONTRACT_STATE
	 * @param contractState  the value for TRX_CONTRACT.CONTRACT_STATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setContractState(Integer contractState) {
		this.contractState = contractState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CONTRACT.NOTE
	 * @return  the value of TRX_CONTRACT.NOTE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CONTRACT.NOTE
	 * @param note  the value for TRX_CONTRACT.NOTE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setNote(String note) {
		this.note = note;
	}

	private String contractStateStr;
	
	public String getContractStateStr() {
		return contractStateStr;
	}

	public void setContractStateStr(String contractStateStr) {
		this.contractStateStr = contractStateStr;
	}
}