package ext.datasource.entity;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import ext.util.helper.CustomDateSerializer;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.SEX
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.AGE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.CARD_TYPE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer cardType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.CARD_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String cardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.PHONE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.ADDRESS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.EMAIL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.PROMOTE_TEACHER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer promoteTeacher;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.PROMOTE_TEACHER_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String promoteTeacherName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.SCHOOL_AREA
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer schoolArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.PROMOTE_ST
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer promoteSt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.PROMOTE_ST_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String promoteStName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer updateOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CUSTOMER.NOTE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String note;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.ID
	 * @return  the value of TRX_CUSTOMER.ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.ID
	 * @param id  the value for TRX_CUSTOMER.ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.NAME
	 * @return  the value of TRX_CUSTOMER.NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.NAME
	 * @param name  the value for TRX_CUSTOMER.NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.SEX
	 * @return  the value of TRX_CUSTOMER.SEX
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.SEX
	 * @param sex  the value for TRX_CUSTOMER.SEX
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.AGE
	 * @return  the value of TRX_CUSTOMER.AGE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.AGE
	 * @param age  the value for TRX_CUSTOMER.AGE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.CARD_TYPE
	 * @return  the value of TRX_CUSTOMER.CARD_TYPE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getCardType() {
		return cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.CARD_TYPE
	 * @param cardType  the value for TRX_CUSTOMER.CARD_TYPE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCardType(Integer cardType) {
		this.cardType = cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.CARD_ID
	 * @return  the value of TRX_CUSTOMER.CARD_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.CARD_ID
	 * @param cardId  the value for TRX_CUSTOMER.CARD_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.PHONE
	 * @return  the value of TRX_CUSTOMER.PHONE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.PHONE
	 * @param phone  the value for TRX_CUSTOMER.PHONE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.ADDRESS
	 * @return  the value of TRX_CUSTOMER.ADDRESS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.ADDRESS
	 * @param address  the value for TRX_CUSTOMER.ADDRESS
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.EMAIL
	 * @return  the value of TRX_CUSTOMER.EMAIL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.EMAIL
	 * @param email  the value for TRX_CUSTOMER.EMAIL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.PROMOTE_TEACHER
	 * @return  the value of TRX_CUSTOMER.PROMOTE_TEACHER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getPromoteTeacher() {
		return promoteTeacher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.PROMOTE_TEACHER
	 * @param promoteTeacher  the value for TRX_CUSTOMER.PROMOTE_TEACHER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setPromoteTeacher(Integer promoteTeacher) {
		this.promoteTeacher = promoteTeacher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.PROMOTE_TEACHER_NAME
	 * @return  the value of TRX_CUSTOMER.PROMOTE_TEACHER_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getPromoteTeacherName() {
		return promoteTeacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.PROMOTE_TEACHER_NAME
	 * @param promoteTeacherName  the value for TRX_CUSTOMER.PROMOTE_TEACHER_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setPromoteTeacherName(String promoteTeacherName) {
		this.promoteTeacherName = promoteTeacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.SCHOOL_AREA
	 * @return  the value of TRX_CUSTOMER.SCHOOL_AREA
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getSchoolArea() {
		return schoolArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.SCHOOL_AREA
	 * @param schoolArea  the value for TRX_CUSTOMER.SCHOOL_AREA
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setSchoolArea(Integer schoolArea) {
		this.schoolArea = schoolArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.PROMOTE_ST
	 * @return  the value of TRX_CUSTOMER.PROMOTE_ST
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getPromoteSt() {
		return promoteSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.PROMOTE_ST
	 * @param promoteSt  the value for TRX_CUSTOMER.PROMOTE_ST
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setPromoteSt(Integer promoteSt) {
		this.promoteSt = promoteSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.PROMOTE_ST_NAME
	 * @return  the value of TRX_CUSTOMER.PROMOTE_ST_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getPromoteStName() {
		return promoteStName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.PROMOTE_ST_NAME
	 * @param promoteStName  the value for TRX_CUSTOMER.PROMOTE_ST_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setPromoteStName(String promoteStName) {
		this.promoteStName = promoteStName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.CREATE_DATE
	 * @return  the value of TRX_CUSTOMER.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.CREATE_DATE
	 * @param createDate  the value for TRX_CUSTOMER.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.UPDATE_DATE
	 * @return  the value of TRX_CUSTOMER.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.UPDATE_DATE
	 * @param updateDate  the value for TRX_CUSTOMER.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.CREATE_OPERATOR
	 * @return  the value of TRX_CUSTOMER.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.CREATE_OPERATOR
	 * @param createOperator  the value for TRX_CUSTOMER.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCreateOperator(Integer createOperator) {
		this.createOperator = createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.UPDATE_OPERATOR
	 * @return  the value of TRX_CUSTOMER.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getUpdateOperator() {
		return updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.UPDATE_OPERATOR
	 * @param updateOperator  the value for TRX_CUSTOMER.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setUpdateOperator(Integer updateOperator) {
		this.updateOperator = updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CUSTOMER.NOTE
	 * @return  the value of TRX_CUSTOMER.NOTE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CUSTOMER.NOTE
	 * @param note  the value for TRX_CUSTOMER.NOTE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setNote(String note) {
		this.note = note;
	}

	private String sexStr;
	public String getSexStr() {
		return sexStr;
	}

	public void setSexStr(String sexStr) {
		this.sexStr = sexStr;
	}

	
	
	
}