package ext.datasource.entity;

public class SDic extends SDicKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_DIC.DIC_DESC
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	private String dicDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_DIC.DIC_CONT
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	private String dicCont;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_DIC.DIC_DESC
	 * @return  the value of S_DIC.DIC_DESC
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public String getDicDesc() {
		return dicDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_DIC.DIC_DESC
	 * @param dicDesc  the value for S_DIC.DIC_DESC
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public void setDicDesc(String dicDesc) {
		this.dicDesc = dicDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_DIC.DIC_CONT
	 * @return  the value of S_DIC.DIC_CONT
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public String getDicCont() {
		return dicCont;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_DIC.DIC_CONT
	 * @param dicCont  the value for S_DIC.DIC_CONT
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public void setDicCont(String dicCont) {
		this.dicCont = dicCont;
	}
}