package ext.datasource.entity;

public class SDicKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_DIC.DIC_NAME
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	private String dicName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_DIC.DIC_VALUE
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	private String dicValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_DIC.DIC_NAME
	 * @return  the value of S_DIC.DIC_NAME
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public String getDicName() {
		return dicName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_DIC.DIC_NAME
	 * @param dicName  the value for S_DIC.DIC_NAME
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public void setDicName(String dicName) {
		this.dicName = dicName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_DIC.DIC_VALUE
	 * @return  the value of S_DIC.DIC_VALUE
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public String getDicValue() {
		return dicValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_DIC.DIC_VALUE
	 * @param dicValue  the value for S_DIC.DIC_VALUE
	 * @mbg.generated  Thu Jun 15 20:37:45 GMT+08:00 2017
	 */
	public void setDicValue(String dicValue) {
		this.dicValue = dicValue;
	}
}