package ext.datasource.entity;

public class SModule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.MODULE_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String moduleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.MODULE_LINK
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String moduleLink;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.IFRAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Boolean iframe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.PARENT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String parent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.ICON
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.DES_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String desName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.M_RIGHT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer mRight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_MODULE.M_ORDER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer mOrder;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.MODULE_NAME
	 * @return  the value of S_MODULE.MODULE_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getModuleName() {
		return moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.MODULE_NAME
	 * @param moduleName  the value for S_MODULE.MODULE_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.MODULE_LINK
	 * @return  the value of S_MODULE.MODULE_LINK
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getModuleLink() {
		return moduleLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.MODULE_LINK
	 * @param moduleLink  the value for S_MODULE.MODULE_LINK
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setModuleLink(String moduleLink) {
		this.moduleLink = moduleLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.IFRAME
	 * @return  the value of S_MODULE.IFRAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Boolean getIframe() {
		return iframe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.IFRAME
	 * @param iframe  the value for S_MODULE.IFRAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setIframe(Boolean iframe) {
		this.iframe = iframe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.PARENT
	 * @return  the value of S_MODULE.PARENT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getParent() {
		return parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.PARENT
	 * @param parent  the value for S_MODULE.PARENT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setParent(String parent) {
		this.parent = parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.ICON
	 * @return  the value of S_MODULE.ICON
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.ICON
	 * @param icon  the value for S_MODULE.ICON
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.DES_NAME
	 * @return  the value of S_MODULE.DES_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getDesName() {
		return desName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.DES_NAME
	 * @param desName  the value for S_MODULE.DES_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setDesName(String desName) {
		this.desName = desName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.M_RIGHT
	 * @return  the value of S_MODULE.M_RIGHT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getmRight() {
		return mRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.M_RIGHT
	 * @param mRight  the value for S_MODULE.M_RIGHT
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setmRight(Integer mRight) {
		this.mRight = mRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_MODULE.M_ORDER
	 * @return  the value of S_MODULE.M_ORDER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getmOrder() {
		return mOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_MODULE.M_ORDER
	 * @param mOrder  the value for S_MODULE.M_ORDER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setmOrder(Integer mOrder) {
		this.mOrder = mOrder;
	}
}