package ext.datasource.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SRoleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public SRoleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andSModuleIsNull() {
			addCriterion("S_MODULE is null");
			return (Criteria) this;
		}

		public Criteria andSModuleIsNotNull() {
			addCriterion("S_MODULE is not null");
			return (Criteria) this;
		}

		public Criteria andSModuleEqualTo(String value) {
			addCriterion("S_MODULE =", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleNotEqualTo(String value) {
			addCriterion("S_MODULE <>", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleGreaterThan(String value) {
			addCriterion("S_MODULE >", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleGreaterThanOrEqualTo(String value) {
			addCriterion("S_MODULE >=", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleLessThan(String value) {
			addCriterion("S_MODULE <", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleLessThanOrEqualTo(String value) {
			addCriterion("S_MODULE <=", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleLike(String value) {
			addCriterion("S_MODULE like", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleNotLike(String value) {
			addCriterion("S_MODULE not like", value, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleIn(List<String> values) {
			addCriterion("S_MODULE in", values, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleNotIn(List<String> values) {
			addCriterion("S_MODULE not in", values, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleBetween(String value1, String value2) {
			addCriterion("S_MODULE between", value1, value2, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleNotBetween(String value1, String value2) {
			addCriterion("S_MODULE not between", value1, value2, "sModule");
			return (Criteria) this;
		}

		public Criteria andSModuleCIsNull() {
			addCriterion("S_MODULE_C is null");
			return (Criteria) this;
		}

		public Criteria andSModuleCIsNotNull() {
			addCriterion("S_MODULE_C is not null");
			return (Criteria) this;
		}

		public Criteria andSModuleCEqualTo(Boolean value) {
			addCriterion("S_MODULE_C =", value, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCNotEqualTo(Boolean value) {
			addCriterion("S_MODULE_C <>", value, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCGreaterThan(Boolean value) {
			addCriterion("S_MODULE_C >", value, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCGreaterThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_C >=", value, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCLessThan(Boolean value) {
			addCriterion("S_MODULE_C <", value, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCLessThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_C <=", value, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCIn(List<Boolean> values) {
			addCriterion("S_MODULE_C in", values, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCNotIn(List<Boolean> values) {
			addCriterion("S_MODULE_C not in", values, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_C between", value1, value2, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleCNotBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_C not between", value1, value2, "sModuleC");
			return (Criteria) this;
		}

		public Criteria andSModuleRIsNull() {
			addCriterion("S_MODULE_R is null");
			return (Criteria) this;
		}

		public Criteria andSModuleRIsNotNull() {
			addCriterion("S_MODULE_R is not null");
			return (Criteria) this;
		}

		public Criteria andSModuleREqualTo(Boolean value) {
			addCriterion("S_MODULE_R =", value, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRNotEqualTo(Boolean value) {
			addCriterion("S_MODULE_R <>", value, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRGreaterThan(Boolean value) {
			addCriterion("S_MODULE_R >", value, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRGreaterThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_R >=", value, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRLessThan(Boolean value) {
			addCriterion("S_MODULE_R <", value, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRLessThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_R <=", value, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRIn(List<Boolean> values) {
			addCriterion("S_MODULE_R in", values, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRNotIn(List<Boolean> values) {
			addCriterion("S_MODULE_R not in", values, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_R between", value1, value2, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleRNotBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_R not between", value1, value2, "sModuleR");
			return (Criteria) this;
		}

		public Criteria andSModuleUIsNull() {
			addCriterion("S_MODULE_U is null");
			return (Criteria) this;
		}

		public Criteria andSModuleUIsNotNull() {
			addCriterion("S_MODULE_U is not null");
			return (Criteria) this;
		}

		public Criteria andSModuleUEqualTo(Boolean value) {
			addCriterion("S_MODULE_U =", value, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleUNotEqualTo(Boolean value) {
			addCriterion("S_MODULE_U <>", value, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleUGreaterThan(Boolean value) {
			addCriterion("S_MODULE_U >", value, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleUGreaterThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_U >=", value, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleULessThan(Boolean value) {
			addCriterion("S_MODULE_U <", value, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleULessThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_U <=", value, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleUIn(List<Boolean> values) {
			addCriterion("S_MODULE_U in", values, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleUNotIn(List<Boolean> values) {
			addCriterion("S_MODULE_U not in", values, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleUBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_U between", value1, value2, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleUNotBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_U not between", value1, value2, "sModuleU");
			return (Criteria) this;
		}

		public Criteria andSModuleDIsNull() {
			addCriterion("S_MODULE_D is null");
			return (Criteria) this;
		}

		public Criteria andSModuleDIsNotNull() {
			addCriterion("S_MODULE_D is not null");
			return (Criteria) this;
		}

		public Criteria andSModuleDEqualTo(Boolean value) {
			addCriterion("S_MODULE_D =", value, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDNotEqualTo(Boolean value) {
			addCriterion("S_MODULE_D <>", value, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDGreaterThan(Boolean value) {
			addCriterion("S_MODULE_D >", value, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDGreaterThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_D >=", value, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDLessThan(Boolean value) {
			addCriterion("S_MODULE_D <", value, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDLessThanOrEqualTo(Boolean value) {
			addCriterion("S_MODULE_D <=", value, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDIn(List<Boolean> values) {
			addCriterion("S_MODULE_D in", values, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDNotIn(List<Boolean> values) {
			addCriterion("S_MODULE_D not in", values, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_D between", value1, value2, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andSModuleDNotBetween(Boolean value1, Boolean value2) {
			addCriterion("S_MODULE_D not between", value1, value2, "sModuleD");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table S_ROLE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table S_ROLE
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 12 22:55:26 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}