package ext.datasource.entity;

import java.util.Date;

public class SRole extends SRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.S_MODULE_C
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String userName;
	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	private Boolean sModuleC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.S_MODULE_R
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Boolean sModuleR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.S_MODULE_U
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Boolean sModuleU;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.S_MODULE_D
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Boolean sModuleD;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Date updateDate;

	private String moduleName;
	
	
	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.S_MODULE_C
	 * @return  the value of S_ROLE.S_MODULE_C
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Boolean getsModuleC() {
		return sModuleC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.S_MODULE_C
	 * @param sModuleC  the value for S_ROLE.S_MODULE_C
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setsModuleC(Boolean sModuleC) {
		this.sModuleC = sModuleC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.S_MODULE_R
	 * @return  the value of S_ROLE.S_MODULE_R
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Boolean getsModuleR() {
		return sModuleR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.S_MODULE_R
	 * @param sModuleR  the value for S_ROLE.S_MODULE_R
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setsModuleR(Boolean sModuleR) {
		this.sModuleR = sModuleR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.S_MODULE_U
	 * @return  the value of S_ROLE.S_MODULE_U
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Boolean getsModuleU() {
		return sModuleU;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.S_MODULE_U
	 * @param sModuleU  the value for S_ROLE.S_MODULE_U
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setsModuleU(Boolean sModuleU) {
		this.sModuleU = sModuleU;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.S_MODULE_D
	 * @return  the value of S_ROLE.S_MODULE_D
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Boolean getsModuleD() {
		return sModuleD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.S_MODULE_D
	 * @param sModuleD  the value for S_ROLE.S_MODULE_D
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setsModuleD(Boolean sModuleD) {
		this.sModuleD = sModuleD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.CREATE_DATE
	 * @return  the value of S_ROLE.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.CREATE_DATE
	 * @param createDate  the value for S_ROLE.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.UPDATE_DATE
	 * @return  the value of S_ROLE.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.UPDATE_DATE
	 * @param updateDate  the value for S_ROLE.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}