package ext.datasource.entity;

public class SRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.USER_ID
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_ROLE.S_MODULE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private String sModule;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.USER_ID
	 * @return  the value of S_ROLE.USER_ID
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.USER_ID
	 * @param userId  the value for S_ROLE.USER_ID
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_ROLE.S_MODULE
	 * @return  the value of S_ROLE.S_MODULE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public String getsModule() {
		return sModule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_ROLE.S_MODULE
	 * @param sModule  the value for S_ROLE.S_MODULE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setsModule(String sModule) {
		this.sModule = sModule;
	}
}