package ext.datasource.entity;

import java.util.Date;

public class SUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_USER.ID
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_USER.USER_NAME
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_USER.USER_PWD
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_USER.CREATE_DATE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_USER.UPDATE_DAATE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private Date updateDaate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_USER.OWN_USER
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	private Integer ownUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_USER.ID
	 * @return  the value of S_USER.ID
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_USER.ID
	 * @param id  the value for S_USER.ID
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_USER.USER_NAME
	 * @return  the value of S_USER.USER_NAME
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_USER.USER_NAME
	 * @param userName  the value for S_USER.USER_NAME
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_USER.USER_PWD
	 * @return  the value of S_USER.USER_PWD
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_USER.USER_PWD
	 * @param userPwd  the value for S_USER.USER_PWD
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_USER.CREATE_DATE
	 * @return  the value of S_USER.CREATE_DATE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_USER.CREATE_DATE
	 * @param createDate  the value for S_USER.CREATE_DATE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_USER.UPDATE_DAATE
	 * @return  the value of S_USER.UPDATE_DAATE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public Date getUpdateDaate() {
		return updateDaate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_USER.UPDATE_DAATE
	 * @param updateDaate  the value for S_USER.UPDATE_DAATE
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setUpdateDaate(Date updateDaate) {
		this.updateDaate = updateDaate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_USER.OWN_USER
	 * @return  the value of S_USER.OWN_USER
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public Integer getOwnUser() {
		return ownUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_USER.OWN_USER
	 * @param ownUser  the value for S_USER.OWN_USER
	 * @mbg.generated  Tue Jun 13 22:26:58 GMT+08:00 2017
	 */
	public void setOwnUser(Integer ownUser) {
		this.ownUser = ownUser;
	}
}