package ext.datasource.entity;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import ext.util.helper.CustomDateSerializer;

import java.math.BigDecimal;

public class TrxClass {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.id
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String className;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.ACADEMIC_YEAR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer academicYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.ACADEMIC_QUARTER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer academicQuarter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_TIME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.SCHOOL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.TEACHER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer teacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.ASS_TEACHER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer assTeacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_MEMBER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer classMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer updateOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.SCHOOL_AREA
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer schoolArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_RATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private BigDecimal classRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_HOUR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer startHour;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_MIN
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer startMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_SCHEDULE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private String startSchedule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_STATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer classState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CURRENT_MEMBER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer currentMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CURRENT_SCHOOL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	private Integer currentSchool;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.id
	 * @return  the value of TRX_CLASS.id
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.id
	 * @param id  the value for TRX_CLASS.id
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CLASS_NAME
	 * @return  the value of TRX_CLASS.CLASS_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CLASS_NAME
	 * @param className  the value for TRX_CLASS.CLASS_NAME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.ACADEMIC_YEAR
	 * @return  the value of TRX_CLASS.ACADEMIC_YEAR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getAcademicYear() {
		return academicYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.ACADEMIC_YEAR
	 * @param academicYear  the value for TRX_CLASS.ACADEMIC_YEAR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setAcademicYear(Integer academicYear) {
		this.academicYear = academicYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.ACADEMIC_QUARTER
	 * @return  the value of TRX_CLASS.ACADEMIC_QUARTER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getAcademicQuarter() {
		return academicQuarter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.ACADEMIC_QUARTER
	 * @param academicQuarter  the value for TRX_CLASS.ACADEMIC_QUARTER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setAcademicQuarter(Integer academicQuarter) {
		this.academicQuarter = academicQuarter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.START_TIME
	 * @return  the value of TRX_CLASS.START_TIME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.START_TIME
	 * @param startTime  the value for TRX_CLASS.START_TIME
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.SCHOOL
	 * @return  the value of TRX_CLASS.SCHOOL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.SCHOOL
	 * @param school  the value for TRX_CLASS.SCHOOL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setSchool(Integer school) {
		this.school = school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.TEACHER_ID
	 * @return  the value of TRX_CLASS.TEACHER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.TEACHER_ID
	 * @param teacherId  the value for TRX_CLASS.TEACHER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.ASS_TEACHER_ID
	 * @return  the value of TRX_CLASS.ASS_TEACHER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getAssTeacherId() {
		return assTeacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.ASS_TEACHER_ID
	 * @param assTeacherId  the value for TRX_CLASS.ASS_TEACHER_ID
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setAssTeacherId(Integer assTeacherId) {
		this.assTeacherId = assTeacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CLASS_MEMBER
	 * @return  the value of TRX_CLASS.CLASS_MEMBER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getClassMember() {
		return classMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CLASS_MEMBER
	 * @param classMember  the value for TRX_CLASS.CLASS_MEMBER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setClassMember(Integer classMember) {
		this.classMember = classMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CREATE_DATE
	 * @return  the value of TRX_CLASS.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CREATE_DATE
	 * @param createDate  the value for TRX_CLASS.CREATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CREATE_OPERATOR
	 * @return  the value of TRX_CLASS.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CREATE_OPERATOR
	 * @param createOperator  the value for TRX_CLASS.CREATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCreateOperator(Integer createOperator) {
		this.createOperator = createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.UPDATE_DATE
	 * @return  the value of TRX_CLASS.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.UPDATE_DATE
	 * @param updateDate  the value for TRX_CLASS.UPDATE_DATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.UPDATE_OPERATOR
	 * @return  the value of TRX_CLASS.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getUpdateOperator() {
		return updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.UPDATE_OPERATOR
	 * @param updateOperator  the value for TRX_CLASS.UPDATE_OPERATOR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setUpdateOperator(Integer updateOperator) {
		this.updateOperator = updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.SCHOOL_AREA
	 * @return  the value of TRX_CLASS.SCHOOL_AREA
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getSchoolArea() {
		return schoolArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.SCHOOL_AREA
	 * @param schoolArea  the value for TRX_CLASS.SCHOOL_AREA
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setSchoolArea(Integer schoolArea) {
		this.schoolArea = schoolArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CLASS_RATE
	 * @return  the value of TRX_CLASS.CLASS_RATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public BigDecimal getClassRate() {
		return classRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CLASS_RATE
	 * @param classRate  the value for TRX_CLASS.CLASS_RATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setClassRate(BigDecimal classRate) {
		this.classRate = classRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.START_HOUR
	 * @return  the value of TRX_CLASS.START_HOUR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getStartHour() {
		return startHour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.START_HOUR
	 * @param startHour  the value for TRX_CLASS.START_HOUR
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setStartHour(Integer startHour) {
		this.startHour = startHour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.START_MIN
	 * @return  the value of TRX_CLASS.START_MIN
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getStartMin() {
		return startMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.START_MIN
	 * @param startMin  the value for TRX_CLASS.START_MIN
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setStartMin(Integer startMin) {
		this.startMin = startMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.START_SCHEDULE
	 * @return  the value of TRX_CLASS.START_SCHEDULE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public String getStartSchedule() {
		return startSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.START_SCHEDULE
	 * @param startSchedule  the value for TRX_CLASS.START_SCHEDULE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setStartSchedule(String startSchedule) {
		this.startSchedule = startSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CLASS_STATE
	 * @return  the value of TRX_CLASS.CLASS_STATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getClassState() {
		return classState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CLASS_STATE
	 * @param classState  the value for TRX_CLASS.CLASS_STATE
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setClassState(Integer classState) {
		this.classState = classState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CURRENT_MEMBER
	 * @return  the value of TRX_CLASS.CURRENT_MEMBER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getCurrentMember() {
		return currentMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CURRENT_MEMBER
	 * @param currentMember  the value for TRX_CLASS.CURRENT_MEMBER
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCurrentMember(Integer currentMember) {
		this.currentMember = currentMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_CLASS.CURRENT_SCHOOL
	 * @return  the value of TRX_CLASS.CURRENT_SCHOOL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public Integer getCurrentSchool() {
		return currentSchool;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_CLASS.CURRENT_SCHOOL
	 * @param currentSchool  the value for TRX_CLASS.CURRENT_SCHOOL
	 * @mbg.generated  Tue Jun 27 11:19:33 GMT+08:00 2017
	 */
	public void setCurrentSchool(Integer currentSchool) {
		this.currentSchool = currentSchool;
	}
}