package ext.datasource.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import ext.util.helper.CustomDateSerializer;

public class TrxDuty {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.CLASS_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private Integer classId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.CUSTOMER_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.GENERATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date generateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.DUTY_STRATEGY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private Integer dutyStrategy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.DUTY_COST
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private BigDecimal dutyCost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.CREATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.CREATE_OPERATOR
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private Integer createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.UPDATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.UPDATE_OPERATOR
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private Integer updateOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_DUTY.CONTRACT_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	private Integer contractId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.ID
	 * @return  the value of TRX_DUTY.ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.ID
	 * @param id  the value for TRX_DUTY.ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.CLASS_ID
	 * @return  the value of TRX_DUTY.CLASS_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Integer getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.CLASS_ID
	 * @param classId  the value for TRX_DUTY.CLASS_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.CUSTOMER_ID
	 * @return  the value of TRX_DUTY.CUSTOMER_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.CUSTOMER_ID
	 * @param customerId  the value for TRX_DUTY.CUSTOMER_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.GENERATE_DATE
	 * @return  the value of TRX_DUTY.GENERATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Date getGenerateDate() {
		return generateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.GENERATE_DATE
	 * @param generateDate  the value for TRX_DUTY.GENERATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setGenerateDate(Date generateDate) {
		this.generateDate = generateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.DUTY_STRATEGY
	 * @return  the value of TRX_DUTY.DUTY_STRATEGY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Integer getDutyStrategy() {
		return dutyStrategy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.DUTY_STRATEGY
	 * @param dutyStrategy  the value for TRX_DUTY.DUTY_STRATEGY
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setDutyStrategy(Integer dutyStrategy) {
		this.dutyStrategy = dutyStrategy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.DUTY_COST
	 * @return  the value of TRX_DUTY.DUTY_COST
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public BigDecimal getDutyCost() {
		return dutyCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.DUTY_COST
	 * @param dutyCost  the value for TRX_DUTY.DUTY_COST
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setDutyCost(BigDecimal dutyCost) {
		this.dutyCost = dutyCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.CREATE_DATE
	 * @return  the value of TRX_DUTY.CREATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.CREATE_DATE
	 * @param createDate  the value for TRX_DUTY.CREATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.CREATE_OPERATOR
	 * @return  the value of TRX_DUTY.CREATE_OPERATOR
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Integer getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.CREATE_OPERATOR
	 * @param createOperator  the value for TRX_DUTY.CREATE_OPERATOR
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setCreateOperator(Integer createOperator) {
		this.createOperator = createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.UPDATE_DATE
	 * @return  the value of TRX_DUTY.UPDATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.UPDATE_DATE
	 * @param updateDate  the value for TRX_DUTY.UPDATE_DATE
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.UPDATE_OPERATOR
	 * @return  the value of TRX_DUTY.UPDATE_OPERATOR
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Integer getUpdateOperator() {
		return updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.UPDATE_OPERATOR
	 * @param updateOperator  the value for TRX_DUTY.UPDATE_OPERATOR
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setUpdateOperator(Integer updateOperator) {
		this.updateOperator = updateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TRX_DUTY.CONTRACT_ID
	 * @return  the value of TRX_DUTY.CONTRACT_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public Integer getContractId() {
		return contractId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TRX_DUTY.CONTRACT_ID
	 * @param contractId  the value for TRX_DUTY.CONTRACT_ID
	 * @mbg.generated  Thu Jun 29 03:14:04 GMT+08:00 2017
	 */
	public void setContractId(Integer contractId) {
		this.contractId = contractId;
	}
}