package ext.core.domain;

import java.math.BigDecimal;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import ext.util.helper.CustomDateSerializer;

public class TrxClassFont {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.id
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_NAME
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private String className;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.ACADEMIC_YEAR
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer academicYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.ACADEMIC_QUARTER
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer academicQuarter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_TIME
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.SCHOOL
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.TEACHER_ID
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer teacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.ASS_TEACHER_ID
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer assTeacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_MEMBER
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer classMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CREATE_DATE
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CREATE_OPERATOR
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.UPDATE_DATE
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.UPDATE_OPERATOR
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer updateOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.SCHOOL_AREA
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer schoolArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_RATE
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private BigDecimal classRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_HOUR
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer startHour;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_MIN
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer startMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.START_SCHEDULE
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private String startSchedule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CLASS_STATE
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer classState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TRX_CLASS.CURRENT_MEMBER
	 * @mbg.generated  Wed Jun 21 18:39:01 GMT+08:00 2017
	 */
	private Integer currentMember;
	
	private String academicYearStr;
	
	private String academicQuarterStr;
	
	private String isFull;
	
	private String classStateStr;
	
	private String teacherName;
	
	private String assTeacherName;
	

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public String getAssTeacherName() {
		return assTeacherName;
	}

	public void setAssTeacherName(String assTeacherName) {
		this.assTeacherName = assTeacherName;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Integer getAcademicYear() {
		return academicYear;
	}

	public void setAcademicYear(Integer academicYear) {
		this.academicYear = academicYear;
	}

	public Integer getAcademicQuarter() {
		return academicQuarter;
	}

	public void setAcademicQuarter(Integer academicQuarter) {
		this.academicQuarter = academicQuarter;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Integer getSchool() {
		return school;
	}

	public void setSchool(Integer school) {
		this.school = school;
	}

	public Integer getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public Integer getAssTeacherId() {
		return assTeacherId;
	}

	public void setAssTeacherId(Integer assTeacherId) {
		this.assTeacherId = assTeacherId;
	}

	public Integer getClassMember() {
		return classMember;
	}

	public void setClassMember(Integer classMember) {
		this.classMember = classMember;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateOperator() {
		return createOperator;
	}

	public void setCreateOperator(Integer createOperator) {
		this.createOperator = createOperator;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getUpdateOperator() {
		return updateOperator;
	}

	public void setUpdateOperator(Integer updateOperator) {
		this.updateOperator = updateOperator;
	}

	public Integer getSchoolArea() {
		return schoolArea;
	}

	public void setSchoolArea(Integer schoolArea) {
		this.schoolArea = schoolArea;
	}

	public BigDecimal getClassRate() {
		return classRate;
	}

	public void setClassRate(BigDecimal classRate) {
		this.classRate = classRate;
	}

	public Integer getStartHour() {
		return startHour;
	}

	public void setStartHour(Integer startHour) {
		this.startHour = startHour;
	}

	public Integer getStartMin() {
		return startMin;
	}

	public void setStartMin(Integer startMin) {
		this.startMin = startMin;
	}

	public String getStartSchedule() {
		return startSchedule;
	}

	public void setStartSchedule(String startSchedule) {
		this.startSchedule = startSchedule;
	}

	public Integer getClassState() {
		return classState;
	}

	public void setClassState(Integer classState) {
		this.classState = classState;
	}

	public Integer getCurrentMember() {
		return currentMember;
	}

	public void setCurrentMember(Integer currentMember) {
		this.currentMember = currentMember;
	}

	public String getAcademicYearStr() {
		return academicYearStr;
	}

	public void setAcademicYearStr(String academicYearStr) {
		this.academicYearStr = academicYearStr;
	}

	public String getAcademicQuarterStr() {
		return academicQuarterStr;
	}

	public void setAcademicQuarterStr(String academicQuarterStr) {
		this.academicQuarterStr = academicQuarterStr;
	}

	public String getIsFull() {
		return isFull;
	}

	public void setIsFull(String isFull) {
		this.isFull = isFull;
	}

	public String getClassStateStr() {
		return classStateStr;
	}

	public void setClassStateStr(String classStateStr) {
		this.classStateStr = classStateStr;
	}
	
	
	

}
